name: edupay
description: A login widget with login/signup functionalities to help speed up development
version: 5.0.0
repository: https://github.com/YosefPalma/flutter_login.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  audio_service: ^0.18.12
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.0.0
  http: ^1.2.0
  intl_phone_number_input: ^0.7.4
  just_audio: ^0.9.36
  jwt_decode: ^0.3.1
  loading_animation_widget: ^1.2.0+4
  phone_numbers_parser: ^8.0.0
  provider: ^6.0.1
  quiver: ^3.0.1
  shared_preferences: ^2.2.2
  sign_in_button: ^3.0.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mockito: ^5.0.16

flutter:
  uses-material-design: true

  assets:
    - img/
    - img/notifica.png

    - assets/audio/Bienvenido.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
